// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Video struct {
	ID              int32
	Title           string
	Description     pgtype.Text
	ThumbnailPath   string
	Path            string
	DurationSeconds int32
	Format          string
	Type            string
	Tags            []string
	Views           pgtype.Int4
	Likes           pgtype.Int4
	UploadedAt      pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Status          pgtype.Text
}
