// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: video.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO video (
    title,
    description,
    thumbnail_path,
    path,
    duration_seconds,
    format,
    type,
    tags
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, description, thumbnail_path, path, duration_seconds, format, type, tags, views, likes, uploaded_at, updated_at, status
`

type CreateVideoParams struct {
	Title           string
	Description     pgtype.Text
	ThumbnailPath   string
	Path            string
	DurationSeconds int32
	Format          string
	Type            string
	Tags            []string
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.Title,
		arg.Description,
		arg.ThumbnailPath,
		arg.Path,
		arg.DurationSeconds,
		arg.Format,
		arg.Type,
		arg.Tags,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ThumbnailPath,
		&i.Path,
		&i.DurationSeconds,
		&i.Format,
		&i.Type,
		&i.Tags,
		&i.Views,
		&i.Likes,
		&i.UploadedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
